#!/usr/bin/env python3
"""
IMU-Camera Extrinsic & Temporal Calibration Analyzer
Reads /tmp/drone_calib.csv generated by the drone_core VIO pipeline.

Usage:
  1. Move the drone around all 3 axes (roll, pitch, yaw) vigorously for ~10 seconds.
  2. Run this script: python3 tools/calibrate_extrinsics.py
"""

import sys
import math
from pathlib import Path

try:
    import numpy as np
except ImportError:
    print("[ERROR] numpy is required. Run: pip3 install numpy")
    sys.exit(1)

LOG_FILE = Path("/tmp/drone_calib.csv")

def analyze_calibration():
    if not LOG_FILE.exists():
        print(f"[ERROR] Log file not found: {LOG_FILE}")
        print("Make sure drone_core is running and has processed frames.")
        return

    data = np.genfromtxt(LOG_FILE, delimiter=',', skip_header=1, invalid_raise=False)
    if len(data) < 50:
        print(f"[ERROR] Not enough data ({len(data)} rows). Wave the drone around more!")
        return

    # Columns: timestamp_ns, mean_gx, mean_gy, mean_gz, flow_dx, flow_dy
    t  = (data[:, 0] - data[0, 0]) * 1e-9  # seconds from start
    gx = data[:, 1]
    gy = data[:, 2]
    gz = data[:, 3]
    dx = data[:, 4]
    dy = data[:, 5]

    # Normalize signals for cross-correlation
    def norm(sig):
        std = np.std(sig)
        return (sig - np.mean(sig)) / std if std > 1e-6 else np.zeros_like(sig)

    gx_n = norm(gx)
    gy_n = norm(gy)
    gz_n = norm(gz)
    dx_n = norm(dx)
    dy_n = norm(dy)

    fps = 1.0 / np.mean(np.diff(t))

    print(f"=== Extrinsic Calibration Analyzer ===")
    print(f"Data points : {len(data)} frames (~{len(data)/fps:.1f} seconds)")
    print(f"Frame rate  : {fps:.1f} Hz\n")

    # Determine Axis Mapping
    print("[1] Spatial Alignment (Extrinsics)")
    
    # Compute full correlation matrix between Gyro (gx, gy, gz) and Flow (dx, dy)
    # We also estimate Roll (flow rotation), but dx, dy is enough for X/Y/Z mapping.
    corr_x = [np.corrcoef(gx_n, dx_n)[0, 1], np.corrcoef(gy_n, dx_n)[0, 1], np.corrcoef(gz_n, dx_n)[0, 1]]
    corr_y = [np.corrcoef(gx_n, dy_n)[0, 1], np.corrcoef(gy_n, dy_n)[0, 1], np.corrcoef(gz_n, dy_n)[0, 1]]
    
    print("  Correlation Matrix (IMU vs Camera Flow):")
    print(f"            Gyro X      Gyro Y      Gyro Z")
    print(f"  Flow X : {corr_x[0]:8.3f}    {corr_x[1]:8.3f}    {corr_x[2]:8.3f}   (Horizontal motion / Yaw)")
    print(f"  Flow Y : {corr_y[0]:8.3f}    {corr_y[1]:8.3f}    {corr_y[2]:8.3f}   (Vertical motion / Pitch)")
    
    print("\n  Axis Detection:")
    best_x = np.argmax(np.abs(corr_x))
    best_y = np.argmax(np.abs(corr_y))
    
    axes = ['X', 'Y', 'Z']
    pitch_corr = corr_y[best_y]
    yaw_corr = corr_x[best_x]
    
    if abs(pitch_corr) > 0.4:
        print(f"  - Camera Pitch (Y-axis) is aligned with IMU Gyro {axes[best_y]}")
        print(f"    (Sign: {'INVERTED' if pitch_corr < 0 else 'POSITIVE'})")
    else:
        print("  - Camera Pitch (Y-axis) -> Unknown (Did you nod the drone up/down?)")

    if abs(yaw_corr) > 0.4:
        print(f"  - Camera Yaw (X-axis)   is aligned with IMU Gyro {axes[best_x]}")
        print(f"    (Sign: {'INVERTED' if yaw_corr < 0 else 'POSITIVE'})")
    else:
        print("  - Camera Yaw (X-axis)   -> Unknown (Did you shake the drone left/right?)")

    pitch_axis = axes[best_y]
    yaw_axis = axes[best_x]

    # Time offset calculation via Cross-Correlation (argmax of cross-correlation)
    print("\n[2] Temporal Alignment (Time Offset)")
    
    # We use the strongest correlated axis to find the time delay
    if abs(pitch_corr) > abs(yaw_corr):
        sig_imu, sig_cam = (gx_n if pitch_axis == 'X' else gy_n), dy_n
        corr_sign = np.sign(pitch_corr)
    else:
        sig_imu, sig_cam = gz_n, dx_n
        corr_sign = np.sign(yaw_corr)

    # Multiply by sign so peaks align positively
    sig_cam = sig_cam * corr_sign

    # Cross correlate
    cross_corr = np.correlate(sig_cam, sig_imu, mode='full')
    lags = np.arange(-len(sig_cam) + 1, len(sig_cam))
    peak_idx = np.argmax(cross_corr)
    lag_frames = lags[peak_idx]
    time_delay_ms = (lag_frames / fps) * 1000.0

    print(f"  Peak Cross-Correlation lag: {lag_frames} frames")
    if lag_frames > 0:
        print(f"  Camera is BEHIND IMU by {time_delay_ms:.1f} ms (Camera delay)")
    elif lag_frames < 0:
        print(f"  Camera is AHEAD of IMU by {abs(time_delay_ms):.1f} ms (IMU delay)")
    else:
        print(f"  Camera and IMU are perfectly synchronized (0 ms delay).")

    print("\nTip: For VIO (like ORB-SLAM3/VINS), you need the IMU-to-Camera Transformation matrix (T_cam_imu).")
    print("This tool confirms the signs and axes, which is 90% of the battle.")

if __name__ == "__main__":
    analyze_calibration()
